language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-susy-flask' ]; then cd .. && eval "mv $currentfolder generator-susy-flask" && cd generator-susy-flask; fi

